name: Build Vue
on:
  push:
  repository_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    env:
      NODE_ENV: production
      NITRO_TARGET: static
      SITE_URL: https://yun.ng
      BUN_INSTALL_CACHE_DIR: ~/.bun/install/cache
      BUN_RUNTIME_TRANSPILER_CACHE_PATH: .cache/transpiler
      NODE_OPTIONS: "--max-old-space-size=10240"
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Cache Bun & build caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.bun/install/cache
            node_modules
          key: ${{ runner.os }}-bun-${{ hashFiles('package.json','bun.lockb') }}-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-bun-${{ hashFiles('package.json','bun.lockb') }}-
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: Install dependencies
        run: bun install
      - name: Generate
        run: bun run generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
