name: Build Vue
on:
  push:
  repository_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    env:
      NODE_ENV: production
      NITRO_TARGET: static
      SITE_URL: https://yun.ng
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - uses: pnpm/action-setup@v4
        with:
          version: latest
      - uses: actions/setup-node@v4
        with:
          cache: 'pnpm'
          cache-dependency-path: './pnpm-lock.yaml'
          node-version: latest
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true