name: Build Vue
on: [ push, workflow_dispatch ]
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    env:
      NITRO_TARGET: static
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: latest
      - run: pnpm install --no-frozen-lockfile
      - run: pnpm generate
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
